package:com.google.android.networkstack.tethering
package:com.android.cts.priv.ctsshim
package:com.realme.link
package:com.google.android.youtube
package:com.coloros.apprecover
package:com.qualcomm.qti.qcolor
package:com.google.android.ext.services
package:com.coloros.onekeylockscreen
package:com.qualcomm.qti.improvetouch.service
package:com.coloros.phonenoareainquire
package:com.oppo.oppopowermonitor
package:com.android.providers.telephony
package:com.android.dynsystem
package:com.coloros.wirelesssettings
package:com.oplus.crashbox
package:com.android.theme.icon.pebble
package:com.google.android.googlequicksearchbox
package:com.heytap.pictorial
package:com.google.android.cellbroadcastservice
package:com.coloros.smartsidebar
package:com.android.providers.calendar
package:com.google.android.permissioncontroller.overlay.oppo
package:com.android.providers.media
package:com.coloros.karaoke
package:com.qti.service.colorservice
package:com.google.android.onetimeinitializer
package:com.google.android.ext.shared
package:com.android.internal.systemui.navbar.gestural_wide_back
package:com.heytap.music
package:com.qualcomm.qti.simcontacts
package:com.qualcomm.qti.modemtestmode
package:com.android.wallpapercropper
package:com.android.wifi.resources.overlay.oplus
package:com.oplus.location
package:com.android.theme.icon.vessel
package:com.android.theme.color.cinnamon
package:com.android.theme.icon_pack.rounded.systemui
package:com.oppoex.afterservice
package:com.oplus.onetrace
package:com.android.theme.icon.taperedrect
package:com.oppo.operationManual
package:com.coloros.simsettings
package:com.android.externalstorage
package:com.qualcomm.uimremoteclient
package:com.android.htmlviewer
package:com.coloros.healthcheck
package:com.qualcomm.qti.uceShimService
package:com.android.companiondevicemanager
package:com.coloros.weather.service
package:com.android.mms.service
package:com.android.providers.downloads
package:com.coloros.providers.downloads.ui
package:com.coloros.athena
package:oplus.frameworkres.overlay.display.product
package:com.coloros.blacklistapp
package:com.android.theme.icon_pack.rounded.android
package:vendor.qti.hardware.cacert.server
package:com.mediatek.omacp
package:com.qualcomm.qti.telephonyservice
package:android.frameworkres.overlay.display.product
package:com.coloros.locationproxy
package:com.android.theme.icon_pack.circular.themepicker
package:com.oplus.eid
package:vendor.qti.iwlan
package:com.google.android.configupdater
package:com.google.android.providers.media.module
package:com.coloros.wifibackuprestore
package:com.google.android.overlay.modules.permissioncontroller
package:com.coloros.logkit
package:com.qualcomm.uimremoteserver
package:com.heytap.openid
package:com.heytap.usercenter
package:com.qti.confuridialer
package:com.coloros.focusmode
package:android.qvaoverlay.common
package:com.google.ar.core
package:com.google.ar.lens
package:com.android.vending
package:com.android.pacprocessor
package:com.android.simappdialog
package:com.coloros.oshare
package:com.dolby.daxservice
package:com.coloros.exsystemservice
package:com.coloros.eyeprotect
package:com.coloros.gesture
package:android.overlay.common
package:com.coloros.scenemode
package:com.android.internal.display.cutout.emulation.hole
package:com.android.certinstaller
package:com.android.theme.color.black
package:com.android.carrierconfig
package:com.google.android.marvin.talkback
package:com.android.theme.color.green
package:com.android.theme.color.ocean
package:com.android.theme.color.space
package:com.wapi.wapicertmanage
package:com.android.internal.systemui.navbar.threebutton
package:com.google.android.apps.work.oobconfig
package:com.qti.qualcomm.datastatusnotification
package:com.coloros.bootreg
package:android
package:com.coloros.screenrecorder
package:com.android.contacts
package:com.qualcomm.qti.callfeaturessetting
package:com.qualcomm.wfd.service
package:com.android.theme.icon_pack.rounded.launcher
package:com.qti.qualcomm.deviceinfo
package:com.ted.number
package:com.coloros.oppoguardelf
package:com.android.mms
package:com.android.mtp
package:com.android.nfc
package:com.android.ons
package:com.android.stk
package:com.android.backupconfirm
package:com.google.android.cellbroadcastreceiver.overlay
package:com.coloros.assistantscreen
package:com.coloros.activation
package:org.codeaurora.ims
package:com.android.statementservice
package:com.google.android.gm
package:android.overlay.target
package:android.autoinstalls.config.oppo
package:com.google.android.apps.tachyon
package:com.realme.securitycheck
package:com.google.android.overlay.gmsconfig.common
package:com.android.settings.intelligence
package:com.google.android.cellbroadcastservice.overlay
package:com.android.internal.systemui.navbar.gestural_extra_wide_back
package:com.google.android.permissioncontroller
package:com.qualcomm.qti.dynamicddsservice
package:com.google.android.setupwizard
package:com.qualcomm.qcrilmsgtunnel
package:com.realme.wellbeing
package:com.android.providers.settings
package:com.android.sharedstoragebackup
package:com.facebook.services
package:com.android.printspooler
package:com.google.android.overlay.gms
package:com.coloros.notificationmanager
package:com.android.theme.icon_pack.filled.settings
package:com.android.wifi.resources.overlay.common
package:com.google.android.overlay.modules.ext.services
package:com.android.incallui
package:com.coloros.ocs.opencapabilityservice
package:com.oppo.multimedia.dolby
package:com.android.se
package:com.android.inputdevices
package:com.google.android.apps.wellbeing
package:com.fido.asm
package:com.coloros.smartdrive
package:com.redteamobile.roaming
package:com.coloros.translate.engine
package:com.android.bips
package:com.qti.dpmserviceapp
package:com.heytap.appplatform
package:com.daemon.shelper
package:com.google.android.captiveportallogin
package:com.android.theme.icon_pack.circular.settings
package:com.google.android.accessibility.soundamplifier
package:com.google.android.overlay.gmsconfig.comms
package:com.qti.xdivert
package:com.coloros.securitykeyboard
package:com.oppo.launcher
package:com.oplus.customize.coreapp
package:com.google.android.apps.docs
package:android.frameworkres.overlay.ZERO_TOUCH
package:com.google.android.apps.maps
package:com.google.android.modulemetadata
package:com.oppo.wifitest
package:oplus
package:com.android.cellbroadcastreceiver
package:com.google.android.webview
package:com.android.theme.icon.teardrop
package:com.coloros.wallpapers
package:android.frameworkres.overlay.Network
package:com.coloros.sau
package:com.coloros.weather2
package:com.google.android.overlay.modules.documentsui
package:com.coloros.encryption
package:com.qualcomm.qti.simsettings
package:com.google.android.networkstack
package:com.android.server.telecom
package:com.google.android.syncadapters.contacts
package:com.color.uiengine
package:com.android.theme.icon_pack.rounded.themepicker
package:com.android.keychain
package:com.qti.snapdragon.qdcm_ff
package:com.android.wifi.resources.overlay.target
package:com.android.chrome
package:com.coloros.compass2
package:com.android.theme.icon_pack.filled.systemui
package:com.google.android.packageinstaller
package:com.nearme.gamecenter
package:com.nearme.statistics.rom
package:com.google.android.gms
package:com.google.android.gsf
package:com.google.android.tag
package:com.google.android.tts
package:com.android.wifi.resources
package:com.android.phone.overlay.common
package:com.android.carrierconfig.overlay.common
package:com.android.calllogbackup
package:com.google.android.partnersetup
package:com.android.systemui.overlay.common
package:com.android.server.telecom.overlay.common
package:com.android.localtransport
package:com.google.android.videos
package:com.google.android.overlay.gmsconfig.gsa
package:com.android.carrierdefaultapp
package:com.dsi.ant.server
package:com.qualcomm.qti.remoteSimlockAuth
package:com.coloros.lockassistant
package:com.android.theme.font.notoserifsource
package:com.android.theme.icon_pack.filled.android
package:com.android.proxyhandler
package:com.android.internal.display.cutout.emulation.waterfall
package:com.qualcomm.qti.workloadclassifier
package:com.android.theme.icon_pack.circular.systemui
package:com.coloros.sceneservice
package:com.coloros.calculator
package:com.google.android.overlay.modules.permissioncontroller.forframework
package:com.google.android.feedback
package:com.google.android.printservice.recommendation
package:com.google.android.apps.photos
package:com.google.android.calendar
package:com.android.managedprovisioning
package:com.oppo.nhs
package:com.oppo.ota
package:com.oppo.sos
package:com.oppo.camera
package:com.tencent.soter.soterserver
package:com.heytap.datamigration
package:com.google.android.documentsui
package:com.google.mainline.telemetry
package:com.facebook.katana
package:com.coloros.uxdesign
package:com.coloros.alarmclock
package:com.android.providers.partnerbookmarks
package:com.android.smspush
package:com.coloros.gamespaceui
package:com.android.wallpaper.livepicker
package:com.coloros.phonemanager
package:com.coloros.securepay
package:com.facebook.system
package:com.coloros.sauhelper
package:com.oppo.engineermode.network
package:com.realme.movieshot
package:com.android.theme.icon.squircle
package:com.coloros.safecenter
package:com.heytap.colorfulengine
package:com.coloros.deepthinker
package:com.google.android.networkstack.permissionconfig
package:com.android.storagemanager
package:com.oppo.qualityprotect
package:com.android.bookmarkprovider
package:com.ses.entitlement.o2
package:com.android.settings
package:com.qualcomm.qti.cne
package:com.qualcomm.qti.ims
package:com.qualcomm.qti.lpa
package:com.heytap.mcs
package:com.google.android.apps.nbu.paisa.user
package:com.google.android.networkstack.overlay
package:com.oppo.engineermode
package:com.android.theme.icon_pack.filled.launcher
package:com.nearme.atlas
package:com.coloros.exserviceui
package:com.google.android.projection.gearhead
package:com.coloros.screenshot
package:com.oppo.bttestmode
package:com.qualcomm.location
package:com.oppo.atlas
package:com.oplus.postmanservice
package:com.android.cts.ctsshim
package:com.coloros.video
package:com.google.android.overlay.modules.modulemetadata.forframework
package:com.android.theme.icon_pack.circular.launcher
package:com.coloros.filemanager
package:com.caf.fmradio
package:com.android.vpndialogs
package:com.coloros.oppomultiapp
package:com.fido.uafclient
package:com.coloros.ocrscanner
package:com.google.android.keep
package:com.coloros.soundrecorder
package:com.android.phone
package:com.android.shell
package:com.android.theme.icon_pack.filled.themepicker
package:com.android.wallpaperbackup
package:com.android.providers.blockednumber
package:com.android.email.partnerprovider
package:com.coloros.ocrservice
package:com.android.providers.userdictionary
package:com.oppo.quicksearchbox
package:com.coloros.healthservice
package:com.qualcomm.qti.seccamservice
package:com.android.hotspot2.osulogin
package:com.google.android.gms.location.history
package:com.android.internal.systemui.navbar.gestural
package:com.android.location.fused
package:com.android.theme.color.orchid
package:com.android.systemui
package:com.google.android.apps.youtube.music
package:com.android.theme.color.purple
package:com.android.bluetoothmidiservice
package:com.qualcomm.qti.poweroffalarm
package:com.qti.ltebc
package:com.facebook.appmanager
package:com.oppo.tzupdate
package:com.oppo.engineermode.camera
package:com.nearme.romupdate
package:com.coloros.floatassistant
package:com.android.carrierconfig.overlay
package:com.coloros.childrenspace
package:com.android.traceur
package:com.google.android.cellbroadcastreceiver
package:com.heytap.cast
package:com.coloros.gallery3d
package:com.qualcomm.qti.server.wigig.tethering.rro
package:com.android.bluetooth
package:com.qualcomm.timeservice
package:com.qualcomm.atfwd
package:com.qualcomm.embms
package:com.android.providers.contacts
package:com.android.theme.icon.roundedrect
package:com.android.internal.systemui.navbar.gestural_narrow_back
package:com.coloros.securitypermission
package:com.android.cellbroadcastreceiver.overlay.common
package:com.android.theme.icon_pack.rounded.settings
package:com.google.android.inputmethod.latin
package:com.oppo.lfeh
package:com.android.theme.icon_pack.circular.android
package:com.google.android.apps.restore